apiVersion: apps/v1
kind: Deployment
metadata:
  name: timesheet-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timesheet-app
  template:
    metadata:
      labels:
        app: timesheet-app
    spec:
      containers:
      - name: timesheet-app
        image: guetatoussama/timesheet-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/timesheetdb
        - name: SPRING_DATASOURCE_USERNAME
          value: timesheet
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: timesheet-service
spec:
  selector:
    app: timesheet-app
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer